---
title: "HW 5"
author: "Vanessa Dinh"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(purrr)
library(ggplot2)
```

## Problem 2

```{r}
url = "https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"

raw_wapo_homocide = 
  read_csv(url) %>% 
  janitor::clean_names()
```
The raw data has 52,179 observations of homicide data displaying city, state, reported homocide date, victim demographics (first name, last name, race, age, and sex), the latitude and longitude of the location of the homocide, and the disposition of the homocide case (open or closed).

```{r}
wapo_homocide =
  raw_wapo_homocide %>% 
  mutate(
    state = case_when(
      city == "Tulsa" & state == "AL" ~ "OK",
      TRUE ~ as.character(state)),
    city_state = paste(city, state, sep = ", "),
    disposition = as.factor(disposition),
    city_state = as.factor(city_state),
    uid = as.factor(uid)
  ) 

unsolved_homocide = 
  wapo_homocide %>% 
  group_by(city_state) %>% 
  summarize(
    num_unsolved_homocide = sum(disposition != "Closed by arrest"),
    num_homocides = n()
    ) 

```

```{r}

balti_homocides =
  unsolved_homocide %>%
  filter(city_state == "Baltimore, MD") 

balti_x = balti_homocides %>% pull(num_unsolved_homocide)
balti_n = balti_homocides %>% pull(num_homocides)

proptest_balti = 
  prop.test(
     balti_x,
     balti_n, 
     alternative = c("two.sided"), 
     conf.level = 0.95,
     correct = TRUE) %>% 
  broom::tidy() %>% 
  janitor::clean_names() %>% 
  select(estimate, conf_low, conf_high)

```

```{r}
prop_test_city = function(x) {
  
  city_df =
  unsolved_homocide %>% 
    filter(city_state == x)
  
  city_x = city_df %>% pull(num_unsolved_homocide)
  city_n = city_df %>% pull(num_homocides)
  
  prop_test_x =
  prop.test(
     city_x,
     city_n, 
     alternative = c("two.sided"), 
     conf.level = 0.95,
     correct = TRUE) %>% 
  broom::tidy() %>% 
  janitor::clean_names() %>% 
  select(estimate, conf_low, conf_high)
  
prop_test_x
}

prop_test_city(unsolved_homocide$city_state[[3]])

map(unsolved_homocide$city_state, prop_test_city)

final_unsolved_df =
  unsolved_homocide %>% 
  mutate(summary = map(city_state, prop_test_city)) %>% 
  unnest(summary)
  
```

```{r}
final_unsolved_df %>% 
  ggplot(aes(x = reorder(city_state, estimate), y = estimate)) +
  geom_point(aes(x = reorder(city_state, estimate), y = estimate), color = "deepskyblue3") +
  geom_errorbar(aes(ymin = conf_low, ymax = conf_high), color = "deepskyblue3", width = 0.5) +
  labs(
    title = "Proportion of Unsolved Homicides Among 50 US Cities",
    x = "US Cities",
    y = "Proportion of Unsolved Homocides"
  ) +
  theme(legend.position = "none") +
  scale_x_discrete(
    guide = guide_axis(angle = 40)
  )
  
```

## Problem 3

```{r}
# sim_power = function(n = 30, mu, sigma = 5) {
#   
#   sim_data = tibble(
#     x = rnorm(n, mean = mu, sd = sigma),
#   )
#   
#   sim_data %>% 
#     summarize(
#       mu_hat = mean(x),
#       signma_hat = sd(x)
#     )
# }
# 
# output = (0, 5000)
# 
# for (i in 1:5000) {
#   output[[i]] = sim_power
# }
# 
# sim_results = bind_rows(output)

```

